upstream api-gateway {
    server api-gateway-service:8080;
}

server {
    listen       80;

    location /auth-server {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_pass http://api-gateway;
    }

    location /gateway {
        rewrite ^/gateway(/.*)?$ $1 break;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_pass http://api-gateway;
    }
    location /api {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_pass http://api-gateway;
    }
    location /login {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_pass http://api-gateway;
    }

    location ~* \.(woff|woff2|ttf|otf|eot)$ {
        add_header Access-Control-Allow-Origin '*';
        types {
            font/woff woff;
            font/woff2 woff2;
            application/font-sfnt ttf;
            application/font-sfnt otf;
            application/vnd.ms-fontobject eot;
        }
        root /usr/share/nginx/html;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri$args $uri$args/ /index.html =404;
    }
}
